### ISSUE TITLE
No module named 'artists'

### ISSUE THREAD

**Issue by caozhzh** [galiboo/galiboo-python#2]
when try the first sample, I encounted an error:
`>>> from galiboo import music`
ModuleNotFoundError: No module named 'artists'
I install by run:
pip install galiboo

**Comment by thecooltechguy** [comment]
Hey we're actually going to be uploading a new version of the library thanks to @joeirimpan 's PR. It should be live on Pypi within an hour. Thanks!

**Comment by thecooltechguy** [comment]
@caozhzh I've just pushed a 0.0.3 version to Pypi, so give it a try and check if it works! :)

**Comment by caozhzh** [comment]
I uninstall and reinstall, now version is 0.0.4,and
`from galiboo import Galiboo`
run successfully
now I'm waiting my API key. -:)

**Comment by thecooltechguy** [comment]
Hey @caozhzh , we've opened up public access to our APIs for all developers due to the huge number of API key requests we got from Hackernews, so you can now get your own API key at https://galiboo.com! Thanks again! :)
